<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRlw66jz\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRlw66jz/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRlw66jz.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRlw66jz\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRlw66jz\appDevDebugProjectContainer([
    'container.build_hash' => 'Rlw66jz',
    'container.build_id' => 'ea5e5e75',
    'container.build_time' => 1560930122,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRlw66jz');
